import numpy as np

print("creating a 1D full array")
a = np.full(3, 79)  #(number of element, element)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print()

print("creating a 1D full array with float data type")
a = np.full(3, 79, dtype=float)  #(number of element, element)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print()

print("creating a 2D full array with float data type")
a = np.full((2, 2), 79, dtype=float)  #(number of element, element)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print()

print("creating a 3D full array with int data type")
a = np.full((2, 2, 3), 79.5, dtype=int)  #(number of element, element)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print()

print("creating a 3D full array with string data type")
a = np.full((2, 2, 3), 79.5, dtype=str)  #(number of element, element)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print()

print("creating a 3D full array with string data type")
a = np.full((2, 2, 3), 'numpy')  #(number of element, element)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print()